# Generated by Django 5.1.4 on 2024-12-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0002_alter_reservation_user_alter_ticket_reservation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["-created_at"]},
        ),
    ]
