# Generated by Django 5.1.4 on 2024-12-24 09:06

import planetarium.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0003_alter_reservation_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="astronomyshow",
            name="image",
            field=models.ImageField(
                null=True, upload_to=planetarium.utils.astronomy_show_image_path
            ),
        ),
        migrations.AlterField(
            model_name="astronomyshow",
            name="theme",
            field=models.ManyToManyField(blank=True, to="planetarium.showtheme"),
        ),
    ]
