# Generated by Django 5.1.4 on 2024-12-29 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0004_astronomyshow_image_alter_astronomyshow_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="astronomyshow",
            name="title",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        255, "The astronomy show title must not exceed 255 characters."
                    ),
                    django.core.validators.MinLengthValidator(
                        1, "The astronomy show title cannot be empty."
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="planetariumdome",
            name="name",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        255, "The planetarium name must not exceed 255 characters."
                    ),
                    django.core.validators.MinLengthValidator(
                        1, "The planetarium name cannot be empty."
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="showtheme",
            name="name",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        255, "The theme name must not exceed 255 characters."
                    ),
                    django.core.validators.MinLengthValidator(
                        1, "The theme name cannot be empty."
                    ),
                ],
            ),
        ),
    ]
